export const clone = value => JSON.parse(JSON.stringify(value));
export const palette = [
 ['section','Section','Layout'],['grid','Grid','Layout'],['tabs','Tabs','Layout'],['modal','Modal','Layout'],
 ['input','Input','Salesforce'],['combobox','Combobox','Salesforce'],['lookup','Lookup','Salesforce'],['button','Button','Salesforce'],['table','Datatable','Salesforce'],['form','Record Form','Salesforce'],
 ['search','Product Search','Custom'],['price','Price Editor','Custom'],['child','Child LWC','Custom']
].map(([type,label,group])=>({type,label,group}));
export const containers = ['section','grid','tabs','modal','form'];
export function makeNode(type,id){const item=palette.find(x=>x.type===type);if(!item)throw Error('Unsupported component');return {id,type,label:item.label,children:[],props:{variant:'neutral',width:'100%',padding:16,color:'#0176d3',value:'',mode:'edit'},data:{object:'Contact',fields:'Name, Email, Phone',relationship:'AccountId',filter:''},rules:[],connections:[],actions:[]};}
export function sample(){const root=makeNode('section','root');root.label='Order Workspace';const form=makeNode('form','details');form.label='Order Details';for(const [type,id,label,value] of [['lookup','customer','Customer','Acme Industries'],['combobox','warehouse','Warehouse','Pune Warehouse'],['input','date','Order Date','2026-10-01']]){const n=makeNode(type,id);n.label=label;n.props.value=value;form.children.push(n);}const table=makeNode('table','items');table.label='Order Items';table.data={object:'OrderItem',fields:'Product, Quantity, UnitPrice, Discount, Total',relationship:'OrderId',filter:''};table.actions=[{id:'a1',type:'Validate',name:'Validate items',error:'Show error'},{id:'a2',type:'Apex',name:'SaveOrder',error:'Stop'},{id:'a3',type:'Refresh',name:'OrderSummary',error:'Continue'}];table.rules=[{id:'r1',field:'Order Status',operator:'equals',value:'Draft',effect:'Visible',join:'AND'}];const search=makeNode('search','search');const delivery=makeNode('section','delivery');delivery.label='Delivery Details';const address=makeNode('input','address');address.label='Delivery Address';address.props.value='MIDC Industrial Area, Pune';delivery.children.push(address);root.children=[form,search,table,delivery];return {schemaVersion:1,name:'Order Workspace',target:'lightning__RecordPage',nodes:[root],versions:[]};}
export function flatten(nodes,depth=0){return nodes.flatMap(n=>[{...n,depth,indent:`padding-left:${depth*16+8}px`},...flatten(n.children,depth+1)]);}
export function find(nodes,id){for(const n of nodes){if(n.id===id)return n;const result=find(n.children,id);if(result)return result;}return null;}
export function remove(nodes,id){for(let i=0;i<nodes.length;i++){if(nodes[i].id===id)return nodes.splice(i,1)[0];const result=remove(nodes[i].children,id);if(result)return result;}return null;}
export function insert(nodes,node,parentId){if(!parentId){nodes.push(node);return;}const parent=find(nodes,parentId);if(!parent||!containers.includes(parent.type))throw Error('Choose a container');parent.children.push(node);}
export function move(nodes,id,parentId){const node=find(nodes,id);if(!node)throw Error('Missing node');if(id===parentId||find(node.children,parentId))throw Error('Cannot move a component inside itself');const target=parentId?find(nodes,parentId):null;if(parentId&&(!target||!containers.includes(target.type)))throw Error('Choose a container');remove(nodes,id);insert(nodes,node,parentId);}
export function validateProject(p){if(!p||p.schemaVersion!==1||typeof p.name!=='string'||!Array.isArray(p.nodes))throw Error('Invalid project file');if(!['lightning__RecordPage','lightning__AppPage','lightning__HomePage','lightning__RecordAction'].includes(p.target))throw Error('Invalid target');const ids=new Set();let count=0;function visit(nodes,depth){if(depth>15)throw Error('Maximum nesting is 15');for(const n of nodes){if(++count>500)throw Error('Maximum 500 components');if(!n||typeof n.id!=='string'||ids.has(n.id)||!palette.some(x=>x.type===n.type)||typeof n.label!=='string'||!Array.isArray(n.children)||!n.props||!n.data||!Array.isArray(n.rules)||!Array.isArray(n.actions)||!Array.isArray(n.connections))throw Error('Invalid component definition');ids.add(n.id);visit(n.children,depth+1);}}visit(p.nodes,0);return p;}
export function ruleMatches(rule,state){const a=state[rule.field],b=rule.value;switch(rule.operator){case 'equals':return String(a)===String(b);case 'not equals':return String(a)!==String(b);case 'contains':return String(a??'').includes(String(b));case 'blank':return a==null||a==='';case 'greater than':return Number(a)>Number(b);default:return false;}}
export function visible(node,state){const rules=node.rules.filter(r=>r.effect==='Visible');if(!rules.length)return true;return rules.reduce((result,r,i)=>i===0?ruleMatches(r,state):(r.join==='OR'?result||ruleMatches(r,state):result&&ruleMatches(r,state)),true);}
