import {palette,containers,componentDefinition,defaultProperties,canContain} from 'c/builderRegistry';
export {registry,palette,containers,componentDefinition,defaultProperties,canContain,isSelectionType} from 'c/builderRegistry';
export {effectiveInputType,inputPattern,inputProperties,validateInputConfig,validateInputValue,selectedValues,selectionOptions,selectionError,validateSelectionConfig,validateProject,ruleMatches,visible} from 'c/builderValidation';
export const clone = value => JSON.parse(JSON.stringify(value));
export function makeNode(type,id){const item=palette.find(x=>x.type===type);if(!item)throw Error('Unsupported component');return {id,type,label:item.label,children:[],props:{variant:'neutral',width:'100%',padding:16,color:'#0176d3',value:'',mode:'edit',...defaultProperties(type)},data:{object:'Contact',fields:'Name, Email, Phone',relationship:'AccountId',filter:''},rules:[],connections:[],actions:[]};}
export function sample(){const root=makeNode('section','root');root.label='Order Workspace';const form=makeNode('form','details');form.label='Order Details';for(const [type,id,label,value] of [['lookup','customer','Customer','Acme Industries'],['combobox','warehouse','Warehouse','Pune Warehouse'],['input','date','Order Date','2026-10-01']]){const n=makeNode(type,id);n.label=label;n.props.value=value;form.children.push(n);}const table=makeNode('table','items');table.label='Order Items';table.data={object:'OrderItem',fields:'Product, Quantity, UnitPrice, Discount, Total',relationship:'OrderId',filter:''};table.actions=[{id:'a1',type:'Validate',name:'Validate items',error:'Show error'},{id:'a2',type:'Apex',name:'SaveOrder',error:'Stop'},{id:'a3',type:'Refresh',name:'OrderSummary',error:'Continue'}];table.rules=[{id:'r1',field:'Order Status',operator:'equals',value:'Draft',effect:'Visible',join:'AND'}];const search=makeNode('search','search');const delivery=makeNode('section','delivery');delivery.label='Delivery Details';const address=makeNode('input','address');address.label='Delivery Address';address.props.value='MIDC Industrial Area, Pune';delivery.children.push(address);root.children=[form,search,table,delivery];return {schemaVersion:1,name:'Order Workspace',target:'lightning__RecordPage',nodes:[root],versions:[]};}
export function flatten(nodes,depth=0){return nodes.flatMap(n=>[{...n,depth,indent:`padding-left:${depth*16+8}px`},...flatten(n.children,depth+1)]);}
export function find(nodes,id){for(const n of nodes){if(n.id===id)return n;const result=find(n.children,id);if(result)return result;}return null;}
export function parentOf(nodes,id,parent=null){for(const node of nodes){if(node.id===id)return parent;const result=parentOf(node.children,id,node);if(result)return result;}return null;}
export function remove(nodes,id){for(let i=0;i<nodes.length;i++){if(nodes[i].id===id)return nodes.splice(i,1)[0];const result=remove(nodes[i].children,id);if(result)return result;}return null;}
export function insert(nodes,node,parentId){if(!parentId){if(!canContain(null,node.type))throw Error('This component requires its matching parent container');nodes.push(node);return;}const parent=find(nodes,parentId);if(!parent||!containers.includes(parent.type))throw Error('Choose a container');if(!canContain(parent.type,node.type))throw Error('Component is not allowed in this container');parent.children.push(node);}
export function move(nodes,id,parentId){const node=find(nodes,id);if(!node)throw Error('Missing node');if(id===parentId||find(node.children,parentId))throw Error('Cannot move a component inside itself');const target=parentId?find(nodes,parentId):null;if(parentId&&(!target||!containers.includes(target.type)))throw Error('Choose a container');if(!canContain(target?.type,node.type))throw Error('Component is not allowed in this container');remove(nodes,id);insert(nodes,node,parentId);}
