import {test} from 'node:test';import assert from 'node:assert/strict';import {tableSamples,defaultTableConfig,newColumn,fieldPaths,tableConfig,tableRows,validateTableConfig,evaluateTableRow,tableOutput} from '../force-app/main/default/lwc/builderTableModel/builderTableModel.js';
function discounts(){const c=defaultTableConfig();for(const [id,type,v] of [['trade','percent',20],['scheme','amount',300],['extra','percent',10],['special','amount',450]])c.columns.push({...newColumn(id),label:id,key:id,inputType:'number',defaultValue:v,discount:type});c.discounts.enabled=true;c.rules=[{id:'d',kind:'discount',enabled:true,effect:'block',message:'Over {value} / {limit}'},{id:'n',kind:'net',enabled:true,effect:'block'}];return c;}
test('nested field picker and empty bound list',()=>{assert.deepEqual(fieldPaths([{Account:{Name:'A'},Price:2,tags:['x']}]),['Account.Name','Price']);const node={props:{},data:{boundSample:[]}};assert.deepEqual(tableRows(node),[]);assert.equal(tableConfig(node).columns.length,0);assert.throws(()=>tableRows({data:{boundSample:{}}}));});
test('per-row inputs and non-mutating nested output',()=>{const c=defaultTableConfig(),row=tableSamples[0],r=evaluateTableRow(row,{quantity:'50'},c);assert.equal(r.values.qty,50);const output=tableOutput(row,{quantity:50},c,r);assert.equal(output.quantity,50);assert.equal(row.quantity,undefined);assert.equal(evaluateTableRow(row,{},c).values.qty,1);assert.deepEqual(output.product,row.product);});
test('stock comparison supports disable warning and custom message',()=>{const c=defaultTableConfig();c.rules=[{id:'s',enabled:true,kind:'compare',left:'qty',operator:'lte',rightKind:'field',right:'stock',effect:'block',message:'Quantity {value}, stock {limit}'}];validateTableConfig(c);let r=evaluateTableRow(tableSamples[0],{quantity:50},c);assert.equal(r.valid,false);assert.equal(r.issues[0].message,'Quantity 50, stock 48');c.rules[0].effect='warn';assert.equal(evaluateTableRow(tableSamples[0],{quantity:50},c).valid,true);c.rules[0].enabled=false;assert.equal(evaluateTableRow(tableSamples[0],{quantity:50},c).issues.length,0);});
test('four mixed discounts: 105 percent invalid, 100 percent allowed',()=>{const c=discounts();validateTableConfig(c);let r=evaluateTableRow(tableSamples[0],{quantity:10},c);assert.equal(r.discounts.discountPercent,105);assert.equal(r.discounts.net,-50);assert.equal(r.valid,false);r=evaluateTableRow(tableSamples[0],{quantity:10,special:400},c);assert.equal(r.discounts.discountPercent,100);assert.equal(r.discounts.net,0);assert.equal(r.valid,true);});
test('sequential and hidden discounts use column order and gross equivalent',()=>{const c=discounts();c.discounts.mode='sequential';c.columns.find(x=>x.id==='trade').visible=false;const r=evaluateTableRow(tableSamples[0],{quantity:10},c);assert.equal(r.discounts.discountAmount,1000);assert.equal(r.discounts.net,0);assert.equal(r.discounts.discountPercent,100);assert.equal(r.valid,true);});
test('zero gross rejects positive amount discounts without division by zero',()=>{const c=discounts();let r=evaluateTableRow(tableSamples[0],{quantity:0,scheme:0,special:0},c);assert.equal(r.discounts.discountPercent,0);assert.equal(r.valid,true);r=evaluateTableRow(tableSamples[0],{quantity:0,scheme:1,special:0},c);assert.equal(r.discounts.discountPercent,null);assert.equal(r.valid,false);});
test('calculated dependencies and circular missing zero-divisor errors',()=>{const c=defaultTableConfig();c.columns.push({...newColumn('gross'),source:'calculated',left:'qty',right:'f2',calculation:'multiply'});validateTableConfig(c);assert.equal(evaluateTableRow(tableSamples[0],{quantity:10},c).values.gross,1000);c.columns.push({...newColumn('ratio'),source:'calculated',left:'gross',right:'qty',calculation:'divide'});assert.equal(evaluateTableRow(tableSamples[0],{quantity:0},c).valid,false);c.columns.find(x=>x.id==='gross').left='ratio';assert.throws(()=>validateTableConfig(c),/circular/);c.columns.pop();assert.throws(()=>validateTableConfig(c),/operand/);});
test('round trip and duplicate keys unsafe paths width rejection',()=>{const c=defaultTableConfig();assert.deepEqual(validateTableConfig(JSON.parse(JSON.stringify(c))),c);c.columns.push({...newColumn('another'),key:'quantity'});assert.throws(()=>validateTableConfig(c),/unique/);c.columns.pop();c.columns[0].path='__proto__.polluted';assert.throws(()=>validateTableConfig(c),/path/);c.columns[0].path='product.Name';c.columns[0].width=999;assert.throws(()=>validateTableConfig(c),/width/);});
