import {test} from 'node:test';import assert from 'node:assert/strict';import {newColumn,defaultTableConfig,validateTableConfig,evaluateTableRow,parseTableFormula,evaluateTableFormula,formatTableFormula,validateFormulaAst} from '../force-app/main/default/lwc/builderTableModel/builderTableModel.js';
function fixture(){const c=defaultTableConfig([]);for(const [id,label] of [['price','Unit Price'],['qty','Qty'],['stock','My Stock'],['d1','Discount 1'],['d2','Discount 2'],['d3','Discount 3'],['gst','GST']])c.columns.push({...newColumn(id),label,source:'field',path:id});for(const [id,label,formulaText] of [['basic','Basic Value','[Unit Price] * [Qty]'],['disc','Discount Amount','[Basic Value] * SUM([Discount 1], [Discount 2], [Discount 3]) / 100'],['pct','Total Discount %','IF([Basic Value] = 0, IF([Discount Amount] = 0, 0, 101), [Discount Amount] / [Basic Value] * 100)'],['tax','Taxable Amount','ROUND([Basic Value] - [Discount Amount], 2)'],['taxgst','Total GST','ROUND([Taxable Amount] * [GST] / 100, 2)'],['final','Final Amount','[Taxable Amount] + [Total GST]']])c.columns.push({...newColumn(id),label,source:'calculated',calculation:'formula',formulaText});c.rules=[{id:'d',kind:'formula',enabled:true,effect:'block',formulaText:'[Total Discount %] > 100',message:'Discount above 100%'},{id:'s',kind:'formula',enabled:true,effect:'block',formulaText:'[Qty] > [My Stock]',message:'Stock exceeded'},{id:'n',kind:'formula',enabled:true,effect:'block',formulaText:'[Taxable Amount] < 0',message:'Negative taxable'}];validateTableConfig(c);return c;}
const a={price:231,qty:21,stock:50,d1:12,d2:31,d3:66,gst:18},b={price:213,qty:32,stock:30,d1:23,d2:14,d3:0,gst:18};
test('A/B example: dependency chain recalculates discount GST final and row rules',()=>{const c=fixture();let r=evaluateTableRow(a,{},c);assert.equal(r.values.basic,4851);assert.equal(r.values.pct,109);assert.equal(r.valid,false);r=evaluateTableRow({...a,d3:56},{},c);assert.equal(r.values.tax,48.51);assert.equal(r.values.taxgst,8.73);assert.equal(r.values.final,57.24);assert.equal(r.valid,true);r=evaluateTableRow(b,{},c);assert.equal(r.values.tax,4294.08);assert.equal(r.values.taxgst,772.93);assert.equal(r.values.final,5067.01);assert.equal(r.valid,false);assert.equal(evaluateTableRow({...b,qty:30},{},c).valid,true);});
test('stable AST IDs survive header rename, JSON and dependency order change',()=>{const c=fixture();c.columns.find(c=>c.id==='price').label='New price';assert.ok(formatTableFormula(c.columns.find(c=>c.id==='basic').formulaAst,c.columns).includes('[New price]'));c.columns.reverse();const restored=JSON.parse(JSON.stringify(c));validateTableConfig(restored);assert.equal(evaluateTableRow({...a,d3:56},{},restored).values.final,57.24);});
test('mixed amount discount and zero-base IF are lazy and enforce combined 100%',()=>{const c=fixture();const col=c.columns.find(c=>c.id==='disc');col.formulaText='[Basic Value] * ([Discount 1] + [Discount 3]) / 100 + [Discount 2]';validateTableConfig(c);let r=evaluateTableRow({price:100,qty:10,stock:20,d1:40,d2:350,d3:30,gst:18},{},c);assert.equal(r.values.pct,105);assert.equal(r.valid,false);r=evaluateTableRow({price:100,qty:0,stock:20,d1:40,d2:0,d3:30,gst:18},{},c);assert.equal(r.values.pct,0);assert.equal(r.values.final,0);assert.equal(r.valid,true);assert.equal(evaluateTableRow({price:100,qty:0,stock:20,d1:0,d2:5,d3:0,gst:18},{},c).valid,false);});
test('operator precedence boolean logic supported functions and signed rounding',()=>{const calc=text=>evaluateTableFormula(parseTableFormula(text,[]),()=>0);assert.equal(calc('2 + 3 * 4'),14);assert.equal(calc('IF(2 > 1 AND NOT FALSE, MAX(2, 5), 1 / 0)'),5);assert.equal(calc('MIN(8, 2) + SUM(1, 2)'),5);assert.equal(calc('ROUND(-1.235, 2)'),-1.24);assert.throws(()=>calc('IF(1, 2, 3)'),/condition/);});
test('unsafe syntax malformed expressions oversized trees and missing references reject',()=>{for(const text of ['window.alert(1)','[unknown]','ROUND(1, 2, 3)','1 +','1;2','eval(1)','2 ** 3'])assert.throws(()=>parseTableFormula(text,[]));assert.throws(()=>parseTableFormula('1'.repeat(4097),[]));assert.throws(()=>validateFormulaAst({type:'ref',id:'missing'},new Set()));assert.throws(()=>validateFormulaAst({type:'call',name:'EVIL',args:[]},new Set()));});
test('formula cycles across legacy operands, zero divisors and boolean column outputs fail',()=>{const c=fixture();c.columns.find(c=>c.id==='basic').formulaText='[Final Amount]';assert.throws(()=>validateTableConfig(c),/circular/);const valid=fixture();valid.columns.push({...newColumn('divide'),source:'calculated',calculation:'formula',formulaText:'1 / 0'});validateTableConfig(valid);assert.equal(evaluateTableRow(b,{},valid).valid,false);valid.columns.at(-1).formulaText='TRUE';validateTableConfig(valid);assert.ok(evaluateTableRow(b,{},valid).issues.some(i=>i.message.includes('must return a number')));});
test('formula validation supports disable and warning; syntax still validates',()=>{const c=fixture();c.rules[0].effect='warn';c.rules[2].enabled=false;assert.equal(evaluateTableRow(a,{},c).valid,true);c.rules[0].formulaText='[Missing] > 0';assert.throws(()=>validateTableConfig(c),/Unknown/);});

test('true triggers error: stock 10 / qty 22; false allows row and explicit valid mode remains supported',()=>{const c=fixture();c.rules=c.rules.filter(r=>r.id==='s');c.rules[0].formulaText='[My Stock] < [Qty]';validateTableConfig(c);assert.equal(evaluateTableRow({...b,stock:10,qty:22},{},c).valid,false);assert.equal(evaluateTableRow({...b,stock:22,qty:10},{},c).valid,true);assert.equal(evaluateTableRow({...b,stock:10,qty:10},{},c).valid,true);c.rules[0].formulaTrigger='valid';c.rules[0].formulaText='[Qty] <= [My Stock]';validateTableConfig(c);assert.equal(evaluateTableRow({...b,stock:10,qty:22},{},c).valid,false);});
