// Serializable design definitions and a sample-only interpreter. No queries, DML or eval.
const copy=v=>JSON.parse(JSON.stringify(v));
const unsafe=new Set(['__proto__','prototype','constructor']);
const nameOK=s=>typeof s==='string'&&/^[A-Za-z][A-Za-z0-9_]*$/.test(s)&&!unsafe.has(s);
const types=['Text','Number','Boolean'];
export const newOutput=(id,kind='Object')=>({id,name:kind==='Object'?'object':kind==='List'?'items':'value',kind,type:'Text',sourceId:'',matchField:'',parentField:'',mode:'field',field:'',inputId:'',constant:'',children:[]});
export function newPack(id){return {id,name:'NewDataPack',description:'',inputs:[],sources:[],output:{...newOutput(id+'_root'),name:'output'},versions:[]};}
export function examplePack(id){const p=newPack(id);p.name='CustomerWorkspace';p.inputs=[{id:id+'_input',name:'recordId',type:'Text',required:true,defaultValue:'a1'}];p.sources=[{id:id+'_account',name:'Customer',object:'Account',fields:'Id, Name',selectedFields:['Id','Name'],filter:'',filters:[{id:id+'_filter',field:'Id',operator:'equals',valueKind:'input',value:id+'_input'}],sortField:'',sortDirection:'ASC',limit:100,sampleJson:JSON.stringify([{Id:'a1',Name:'Acme'},{Id:'a2',Name:'Other Customer'}],null,2)},{id:id+'_contact',name:'Contacts',object:'Contact',fields:'Id, Name, Email, AccountId',selectedFields:['Id','Name','Email','AccountId'],filter:'',filters:[],sortField:'Name',sortDirection:'ASC',limit:100,sampleJson:JSON.stringify([{Id:'c1',Name:'Alex',Email:'alex@example.com',AccountId:'a1'},{Id:'c2',Name:'Sam',Email:'sam@example.com',AccountId:'a2'}],null,2)}];const leaf=(suffix,name,field)=>({...newOutput(id+suffix,'Value'),name,field});p.output.children=[{...newOutput(id+'_customer'),name:'customer',sourceId:id+'_account',children:[leaf('_cid','id','Id'),leaf('_cname','name','Name'),{...newOutput(id+'_contacts','List'),name:'contacts',sourceId:id+'_contact',matchField:'AccountId',parentField:'Id',children:[leaf('_id','id','Id'),leaf('_name','name','Name'),leaf('_email','email','Email')]}]}];return p;}
export function outputRows(root,depth=0,path=''){const here=path?`${path}.${root.name}`:root.name;return [{...root,depth,path:here,indent:`padding-left:${depth*18+10}px`} ,...root.children.flatMap(n=>outputRows(n,depth+1,root.kind==='List'?here+'[]':here))];}
export function findOutput(root,id){if(root.id===id)return root;for(const c of root.children){const n=findOutput(c,id);if(n)return n;}return null;}
export function removeOutput(root,id){const i=root.children.findIndex(c=>c.id===id);if(i>=0){root.children.splice(i,1);return true;}return root.children.some(c=>removeOutput(c,id));}
export function checkShape(pack){if(!pack||typeof pack.id!=='string'||typeof pack.name!=='string'||!Array.isArray(pack.inputs)||!Array.isArray(pack.sources)||!Array.isArray(pack.versions))throw Error('Invalid data pack definition');if(pack.inputs.length>50||pack.sources.length>30||pack.versions.length>10)throw Error('Data pack limits: 50 inputs, 30 sources, 10 versions');const ids=new Set();for(const x of [...pack.inputs,...pack.sources]){if(!x||typeof x.id!=='string'||ids.has(x.id)||typeof x.name!=='string')throw Error('Invalid or duplicate input/source ID');ids.add(x.id);}for(const s of pack.sources){if(!Array.isArray(s.filters)||s.filters.length>50||typeof s.sampleJson!=='string'||s.sampleJson.length>250000)throw Error('Invalid source filters or sample size');}let count=0;function walk(n,depth){if(!n||typeof n.id!=='string'||ids.has(n.id)||typeof n.name!=='string'||!['Object','List','Value'].includes(n.kind)||!Array.isArray(n.children)||depth>10||++count>200)throw Error('Invalid output tree; limits: 10 levels, 200 nodes');ids.add(n.id);if(n.kind==='Value'&&n.children.length)throw Error('Value nodes cannot contain children');n.children.forEach(c=>walk(c,depth+1));}walk(pack.output,0);if(pack.output.name!=='output')throw Error('Output root name must be output');if(pack.output.kind!=='Object')throw Error('Output root must be an Object');for(const v of pack.versions){if(!v||!Number.isInteger(v.version)||!v.definition||v.definition.versions!==undefined)throw Error('Invalid published snapshot');checkShape({...v.definition,versions:[]});}return pack;}
export function validatePack(pack){checkShape(pack);const issues=[];const add=(path,msg)=>issues.push({path,message:msg});if(!nameOK(pack.name))add('Pack','Use a name starting with a letter, then letters, numbers or underscores.');const seen=new Set();for(const input of pack.inputs){if(!nameOK(input.name)||seen.has(input.name))add('Inputs','Invalid or duplicate input name: '+input.name);seen.add(input.name);if(!types.includes(input.type))add(input.name,'Invalid input type.');}seen.clear();const sources=new Map(pack.sources.map(s=>[s.id,s]));const inputIds=new Set(pack.inputs.map(i=>i.id));for(const s of pack.sources){if(!nameOK(s.name)||seen.has(s.name))add('Sources','Invalid or duplicate source name: '+s.name);seen.add(s.name);if(!s.object)add(s.name,'Select a source object.');if(!Number.isInteger(Number(s.limit))||Number(s.limit)<1||Number(s.limit)>500)add(s.name,'Row limit must be 1–500.');try{const rows=JSON.parse(s.sampleJson);if(!Array.isArray(rows)||rows.length>500||rows.some(r=>!r||typeof r!=='object'||Array.isArray(r)))throw Error();}catch{add(s.name,'Sample data must be an array of at most 500 record objects.');}if(s.relatedSource)add(s.name,'Related context is not executed in sample preview. Configure a filter or output join, then clear related context.');if(s.filter)add(s.name,'Legacy filter text needs conversion to visual filters before publishing.');for(const f of s.filters){if(!f.field||!['equals','not equals','contains','greater than','blank'].includes(f.operator)||!['input','constant'].includes(f.valueKind))add(s.name,'Incomplete filter.');if(f.valueKind==='input'&&!inputIds.has(f.value))add(s.name,'Filter input is missing.');}}
function walk(n,path,hasRecord){if(!nameOK(n.name))add(path,'Invalid output name.');if(n.sourceId&&!sources.has(n.sourceId))add(path,'Source is missing.');if(n.kind==='List'&&!n.sourceId)add(path,'A list needs a source.');if(Boolean(n.matchField)!==Boolean(n.parentField))add(path,'Both parent key and matching field are required.');if(n.matchField&&!hasRecord)add(path,'Join requires a parent source record.');const record=Boolean(n.sourceId)||hasRecord;if(n.kind==='Value'){if(!types.includes(n.type))add(path,'Select a value type.');if(!['field','input','constant','count'].includes(n.mode))add(path,'Invalid mapping mode.');if(n.mode==='field'&&(!n.field||!hasRecord))add(path,'Field mapping needs a field and enclosing source record.');if(n.mode==='input'&&!inputIds.has(n.inputId))add(path,'Select an input.');if(n.mode==='count'&&(!n.sourceId||!sources.has(n.sourceId)))add(path,'Count needs a source.');}else{if(!n.children.length)add(path,'Add output children.');const names=new Set();for(const c of n.children){if(names.has(c.name))add(path,'Duplicate child name: '+c.name);names.add(c.name);walk(c,path+'.'+c.name,record);}}}walk(pack.output,'output',false);return issues;}
function read(row,path){return String(path||'').split('.').reduce((value,key)=>unsafe.has(key)?undefined:value?.[key],row);}
function cast(value,type,path){if(value===null||value===undefined)return null;if(type==='Text')return String(value);if(type==='Number'){if(typeof value==='boolean'||String(value).trim()===''||!Number.isFinite(Number(value)))throw Error(path+': expected Number');return Number(value);}if(type==='Boolean'){if(value===true||value==='true')return true;if(value===false||value==='false')return false;throw Error(path+': expected Boolean');}throw Error(path+': unknown type');}
export function runSample(pack,inputValues={}){const issues=validatePack(pack);if(issues.length)throw Error(issues.map(i=>i.path+': '+i.message).join('\n'));const inputs={};for(const i of pack.inputs){const raw=Object.prototype.hasOwnProperty.call(inputValues,i.id)?inputValues[i.id]:i.defaultValue;if(i.required&&(raw===undefined||raw===null||raw===''))throw Error('Required input: '+i.name);inputs[i.id]=raw===''?null:cast(raw,i.type,i.name);}const records=new Map();const execution=[];for(const s of pack.sources){let rows=JSON.parse(s.sampleJson);for(const f of s.filters){const target=f.valueKind==='input'?inputs[f.value]:f.value;rows=rows.filter(r=>{const actual=read(r,f.field);switch(f.operator){case 'equals':return actual!=null&&target!=null&&String(actual)===String(target);case 'not equals':return String(actual??'')!==String(target??'');case 'contains':return String(actual??'').includes(String(target??''));case 'greater than':return Number(actual)>Number(target);case 'blank':return actual==null||actual==='';default:return false;}});}if(s.sortField)rows.sort((a,b)=>{const x=read(a,s.sortField),y=read(b,s.sortField);const result=typeof x==='number'&&typeof y==='number'?x-y:String(x??'').localeCompare(String(y??''));return s.sortDirection==='DESC'?-result:result;});rows=rows.slice(0,Number(s.limit));records.set(s.id,rows);execution.push({id:s.id,name:s.name,rows:rows.length,mode:'Sample only'});}
function assemble(n,parent,path){let rows=n.sourceId?records.get(n.sourceId):null;if(rows&&n.matchField){const key=read(parent,n.parentField);rows=key==null?[]:rows.filter(r=>read(r,n.matchField)!=null&&String(read(r,n.matchField))===String(key));}if(n.kind==='Value'){let value;if(n.mode==='field'){const fields=(parent||{});value=read(fields,n.field);if(value===undefined)throw Error(path+': sample field missing: '+n.field);}else if(n.mode==='input')value=inputs[n.inputId];else if(n.mode==='constant')value=n.constant;else value=(rows||[]).length;return cast(value,n.type,path);}const object=row=>Object.fromEntries(n.children.map(c=>[c.name,assemble(c,row,path+'.'+c.name)]));if(n.kind==='List')return (rows||[]).map(r=>object(r));if(rows){if(rows.length>1)throw Error(path+': Object received multiple records. Narrow the filter or use a List.');return rows.length?object(rows[0]):null;}return object(parent);}return {output:assemble(pack.output,null,'output'),execution};}
export function publishSampleVersion(pack,inputValues){runSample(pack,inputValues);const version=Math.max(0,...pack.versions.map(v=>v.version))+1;const definition=copy(pack);delete definition.versions;const snapshot={version,date:new Date().toISOString(),definition};return {...copy(pack),versions:[...pack.versions,snapshot].slice(-10)};}
export function bindablePaths(pack){return outputRows(pack.output).map(row=>({...row,bindingPath:row.path.replace(/^output\.?/,'')})).filter(row=>row.bindingPath);}
export function validatePackCollection(packs){if(packs===undefined)return;if(!Array.isArray(packs)||packs.length>30)throw Error('Maximum 30 data packs per project');const ids=new Set();for(const p of packs){checkShape(p);if(ids.has(p.id))throw Error('Duplicate data pack ID');ids.add(p.id);}}
export function resolveBinding(packs,binding){const pack=packs.find(p=>p.id===binding.packId);const version=pack?.versions.find(v=>v.version===Number(binding.version));if(!version)throw Error('Select a published sample version');const result=runSample({...version.definition,versions:[]},binding.inputValues||{});if(!binding.outputPath||binding.outputPath.includes('[]'))throw Error('Bind an Object, List, or Value outside a repeating item');return read(result.output,binding.outputPath);}
