function numeric(v){if(v===''||v===null||v===undefined||typeof v==='boolean'||typeof v==='object'||!Number.isFinite(Number(v)))throw Error('A numeric value is required');return Number(v);}
// Small expression language. No eval, Function constructor or JavaScript access.
export function parseTableFormula(text,columns,typed=false){if(typeof text!=='string'||!text.trim()||text.length>4096)throw Error('Formula must contain 1–4096 characters');const tokens=[];let i=0;while(i<text.length){const rest=text.slice(i);let m;if(/^\s/.test(rest)){i++;continue;}if((m=rest.match(/^\[([^\]]+)\]/))){const matches=columns.filter(c=>c.label.toLowerCase()===m[1].trim().toLowerCase());if(matches.length!==1)throw Error(matches.length?'Ambiguous header: '+m[1]:'Unknown header: '+m[1]);tokens.push({type:'ref',id:matches[0].id});}else if(typed&&(m=rest.match(/^"(?:[^"\\]|\\.)*"/))){tokens.push({type:'text',value:JSON.parse(m[0])});}else if((m=rest.match(/^(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?/)))tokens.push({type:'number',value:Number(m[0])});else if((m=rest.match(/^[A-Za-z_]+/)))tokens.push({type:m[0].toUpperCase()});else if((m=rest.match(/^(<=|>=|!=|==|[+*/(),<>=-])/)))tokens.push({type:m[0]});else throw Error('Unexpected character at '+(i+1));i+=m[0].length;if(tokens.length>512)throw Error('Formula is too complex');}let p=0,depth=0;const take=t=>tokens[p]?.type===t?(p++,true):false;function primary(){if(++depth>50)throw Error('Formula nesting exceeds 50');const t=tokens[p++];let result;if(!t)throw Error('Incomplete formula');if(t.type==='number'||t.type==='ref'||(typed&&t.type==='text'))result=t;else if(['TRUE','FALSE'].includes(t.type))result={type:'boolean',value:t.type==='TRUE'};else if(['+','-','NOT'].includes(t.type))result={type:'unary',op:t.type,arg:primary()};else if(t.type==='('){result=or();if(!take(')'))throw Error('Missing )');}else if([...['IF','ROUND','SUM','MIN','MAX'],...(typed?['DATE']:[])].includes(t.type)&&take('(')){const args=[];if(!take(')')){do{args.push(or());}while(take(','));if(!take(')'))throw Error('Missing function )');}if((t.type==='DATE'&&args.length!==1)||(t.type==='IF'&&args.length!==3)||(t.type==='ROUND'&&(args.length<1||args.length>2))||(['SUM','MIN','MAX'].includes(t.type)&&!args.length))throw Error('Invalid argument count for '+t.type);result={type:'call',name:t.type,args};}else throw Error('Expected a number, header token or supported function');depth--;return result;}
 function binary(next,ops){let a=next();while(ops.includes(tokens[p]?.type)){const op=tokens[p++].type;a={type:'binary',op,left:a,right:next()};}return a;}const multiply=()=>binary(primary,['*','/']),add=()=>binary(multiply,['+','-']);function comparison(){let a=add();if(['<=','>=','<','>','=','==','!='].includes(tokens[p]?.type)){const op=tokens[p++].type;a={type:'binary',op,left:a,right:add()};}return a;}const and=()=>binary(comparison,['AND']),or=()=>binary(and,['OR']);const ast=or();if(p!==tokens.length)throw Error('Unexpected formula token');return ast;}
export function formulaReferences(ast){if(!ast)return [];if(ast.type==='ref')return [ast.id];if(ast.type==='binary')return [...formulaReferences(ast.left),...formulaReferences(ast.right)];if(ast.type==='unary')return formulaReferences(ast.arg);if(ast.type==='call')return ast.args.flatMap(formulaReferences);return [];}
export function validateFormulaAst(ast,ids,depth=0,budget={count:0}){if(!ast||typeof ast!=='object'||depth>50||++budget.count>512)throw Error('Invalid or excessive formula tree');const next=a=>validateFormulaAst(a,ids,depth+1,budget);if(ast.type==='ref'){if(!ids.has(ast.id))throw Error('Formula references a missing column');}else if(ast.type==='number'){if(typeof ast.value!=='number'||!Number.isFinite(ast.value))throw Error('Invalid formula number');}else if(ast.type==='text'||ast.type==='date'){assertType(ast.value,ast.type==='date'?'Date':'Text');}else if(ast.type==='boolean'){if(typeof ast.value!=='boolean')throw Error('Invalid formula boolean');}else if(ast.type==='unary'){if(!['+','-','NOT'].includes(ast.op))throw Error('Invalid unary operator');next(ast.arg);}else if(ast.type==='binary'){if(!['+','-','*','/','<=','>=','<','>','=','==','!=','AND','OR'].includes(ast.op))throw Error('Invalid formula operator');next(ast.left);next(ast.right);}else if(ast.type==='call'){if(!Array.isArray(ast.args)||!['IF','ROUND','SUM','MIN','MAX','DATE'].includes(ast.name)||(ast.name==='DATE'&&ast.args.length!==1)||(ast.name==='IF'&&ast.args.length!==3)||(ast.name==='ROUND'&&(ast.args.length<1||ast.args.length>2))||(['SUM','MIN','MAX'].includes(ast.name)&&!ast.args.length))throw Error('Invalid formula function');ast.args.forEach(next);}else throw Error('Invalid formula tree');return ast;}
export function formatTableFormula(ast,columns){const refs=new Map(columns.map(c=>[c.id,c.label]));function print(a){if(!a)return '';if(a.type==='ref')return '['+(refs.get(a.id)||'Missing column')+']';if(a.type==='number')return String(a.value);if(a.type==='boolean')return a.value?'TRUE':'FALSE';if(a.type==='unary')return '('+a.op+' '+print(a.arg)+')';if(a.type==='binary')return '('+print(a.left)+' '+a.op+' '+print(a.right)+')';if(a.type==='call')return a.name+'('+a.args.map(print).join(', ')+')';return '';}return print(ast);}
export function evaluateTableFormula(ast,get){const bool=v=>{if(typeof v!=='boolean')throw Error('A condition must return true or false');return v;};const clean=n=>Number.isFinite(n)?Number(n.toPrecision(15)):n;const result=a=>{if(a.type==='number'||a.type==='boolean')return a.value;if(a.type==='ref')return get(a.id);if(a.type==='unary'){const v=result(a.arg);return a.op==='NOT'?!bool(v):a.op==='-'?-numeric(v):numeric(v);}if(a.type==='call'){if(a.name==='IF')return bool(result(a.args[0]))?result(a.args[1]):result(a.args[2]);const values=a.args.map(v=>numeric(result(v)));if(a.name==='ROUND'){const d=values[1]??0;if(!Number.isInteger(d)||d<0||d>8)throw Error('ROUND precision must be 0–8');const f=10**d;return Math.sign(values[0])*Math.round((Math.abs(values[0])+Number.EPSILON)*f)/f;}return a.name==='SUM'?clean(values.reduce((s,v)=>s+v,0)):a.name==='MIN'?Math.min(...values):Math.max(...values);}if(a.op==='AND')return bool(result(a.left))&&bool(result(a.right));if(a.op==='OR')return bool(result(a.left))||bool(result(a.right));const l=numeric(result(a.left)),r=numeric(result(a.right));switch(a.op){case '+':return clean(l+r);case '-':return clean(l-r);case '*':return clean(l*r);case '/':if(r===0)throw Error('Division by zero');return clean(l/r);case '<=':return l<=r;case '>=':return l>=r;case '<':return l<r;case '>':return l>r;case '=':case '==':return l===r;case '!=':return l!==r;}throw Error('Invalid formula operator');};const value=result(ast);if(typeof value==='number'&&!Number.isFinite(value))throw Error('Calculation exceeds numeric range');return value;}

// Typed behavior expressions are opt-in; legacy table numeric coercion remains unchanged.
export function assertType(value,type,nullable=false){
 if(nullable&&value===null)return value;
 const validDate=s=>typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&Number.isFinite(Date.parse(s+'T00:00:00Z'))&&new Date(s+'T00:00:00Z').toISOString().slice(0,10)===s;
 const checks={Number:v=>typeof v==='number'&&Number.isFinite(v),Text:v=>typeof v==='string',Boolean:v=>typeof v==='boolean',Date:validDate,List:Array.isArray,Object:v=>v!==null&&typeof v==='object'&&!Array.isArray(v)};
 if(!checks[type]||!checks[type](value))throw Error('Expected '+type);return value;
}
export function parseExpression(text,references=[]){return parseTableFormula(text,references,true);}
export function evaluateExpression(ast,get,types={}){
 validateFormulaAst(ast,new Set(formulaReferences(ast)));
 const clean=n=>Number.isFinite(n)?Number(n.toPrecision(15)):n;
 function run(a){
  if(['number','boolean','text','date'].includes(a.type)){const type={number:'Number',boolean:'Boolean',text:'Text',date:'Date'}[a.type];assertType(a.value,type);return {type,value:a.value};}
  if(a.type==='ref'){if(!Object.prototype.hasOwnProperty.call(types,a.id))throw Error('Missing typed reference: '+a.id);const value=get(a.id);assertType(value,types[a.id]);return {type:types[a.id],value};}
  const number=x=>{assertType(x.value,'Number');return x.value;},boolean=x=>{assertType(x.value,'Boolean');return x.value;};
  if(a.type==='unary'){const x=run(a.arg);return a.op==='NOT'?{type:'Boolean',value:!boolean(x)}:{type:'Number',value:a.op==='-'?-number(x):number(x)};}
  if(a.type==='call'){
   if(a.name==='DATE'){const x=run(a.args[0]);assertType(x.value,'Date');return {type:'Date',value:x.value};}
   if(a.name==='IF')return boolean(run(a.args[0]))?run(a.args[1]):run(a.args[2]);
   const args=a.args.map(v=>number(run(v)));const value=evaluateTableFormula({...a,args:args.map(v=>({type:'number',value:v}))},()=>undefined);return {type:'Number',value};
  }
  const left=run(a.left);
  if(a.op==='AND')return {type:'Boolean',value:boolean(left)&&boolean(run(a.right))};
  if(a.op==='OR')return {type:'Boolean',value:boolean(left)||boolean(run(a.right))};
  const right=run(a.right),l=left.value,r=right.value;
  if(['=','==','!=','<','>','<=','>='].includes(a.op)){
   if(left.type!==right.type||!['Number','Text','Boolean','Date'].includes(left.type))throw Error('Comparison operands must have the same scalar type');
   if(left.type==='Boolean'&&!['=','==','!='].includes(a.op))throw Error('Boolean ordering is unsupported');
   return {type:'Boolean',value:({'=':l===r,'==':l===r,'!=':l!==r,'<':l<r,'>':l>r,'<=':l<=r,'>=':l>=r})[a.op]};
  }
  number(left);number(right);if(a.op==='/'&&r===0)throw Error('Division by zero');const value=({'+' :()=>clean(l+r),'-':()=>clean(l-r),'*':()=>clean(l*r),'/':()=>clean(l/r)})[a.op]();assertType(value,'Number');return {type:'Number',value};
 }
 const result=run(ast);assertType(result.value,result.type);return result.value;
}
