import {LightningElement,api} from 'lwc';
import {tableConfig,tableRows,fieldPaths,newColumn,validateTableConfig,formatTableFormula,formulaReferences,parseTableFormula} from 'c/builderTableModel';
export default class BuilderTableEditor extends LightningElement {
 _node;signature='';config;selected='';active='Cell';error='';dirty=false;_selectedColumn;@api paths=[];
 @api get node(){return this._node;}set node(n){this._node=n;const signature=JSON.stringify([n.id,n.props.tableConfig,n.data.boundSample,n.data.boundError]);if(signature!==this.signature){this.signature=signature;this.config=tableConfig(n);this.config.totals=this.config.totals||{enabled:false,scope:'all'};if(!this.config.columns.some(c=>c.id===this.selected))this.selected=this.config.columns[0]?.id||'';this.dirty=false;this.error='';}}
 @api get selectedColumnId(){return this._selectedColumn;}set selectedColumnId(v){this._selectedColumn=v;if(this.config?.columns.some(c=>c.id===v)){this.selected=v;this.active='Cell';}}
 get tabs(){return ['Cell','Design','Calculate','Rules'].map(label=>({label,cls:label===this.active?'active':''}));}get showColumns(){return this.isCell||this.isCalculate||this.isDesign;}get isCell(){return this.active==='Cell';}get isDesign(){return this.active==='Design';}get isCalculate(){return this.active==='Calculate';}get isRules(){return this.active==='Rules';}
 get current(){return this.config?.columns.find(c=>c.id===this.selected);}get hasCurrent(){return !!this.current;}get isField(){return this.current?.source==='field';}get isInput(){return this.current?.source==='input';}get isCalculated(){return this.current?.source==='calculated';}get defaultCheckbox(){return this.current?.inputType==='checkbox';}get defaultChecked(){return this.current?.defaultValue===true;}get isNumeric(){return this.current?.inputType==='number';}get isFormula(){return this.isCalculated&&this.current.calculation==='formula';}get formulaText(){return this.current?.formulaText??formatTableFormula(this.current?.formulaAst,this.config.columns);}get tokens(){return this.config.columns.filter(c=>c.id!==this.selected).map(c=>({id:c.id,label:c.label}));}get math(){return this.isCalculated&&['add','subtract','multiply','divide'].includes(this.current.calculation);}get atStart(){return this.config.columns[0]?.id===this.selected;}get atEnd(){return this.config.columns.at(-1)?.id===this.selected;}
 get columns(){return this.config.columns.map(c=>({...c,cls:c.id===this.selected?'chosen':''}));}
 options(values,current){return values.map(value=>({value,label:value,selected:value===current}));}
 get sources(){return this.options(['field','input','calculated'],this.current?.source);}get inputTypes(){return this.options(['text','number','date','checkbox','email','tel'],this.current?.inputType);}get aligns(){return this.options(['left','center','right'],this.current?.align);}get discountTypes(){return this.options(['none','amount','percent'],this.current?.discount);}get calculations(){return this.options(['formula','add','subtract','multiply','divide','gross','discountAmount','discountPercent','net'],this.current?.calculation);}
 get allPaths(){let paths=[];try{paths=fieldPaths(tableRows(this.node));}catch(e){/* Show schema paths even without a sample. */}return [...new Set([...(this.paths||[]),...paths,this.current?.path].filter(Boolean))].sort();}get fieldOptions(){return this.options(this.allPaths,this.current?.path);}
 refs(selected,exclude=''){return this.config.columns.filter(c=>c.id!==exclude).map(c=>({value:c.id,label:c.label,selected:c.id===selected}));}get leftOptions(){return this.refs(this.current?.left,this.selected);}get rightOptions(){return this.refs(this.current?.right,this.selected);}get quantityOptions(){return this.refs(this.config.discounts.quantity);}get priceOptions(){return this.refs(this.config.discounts.price);}get modes(){return this.options(['same','sequential'],this.config.discounts.mode);}get densities(){return this.options(['comfortable','compact'],this.config.density);}get selections(){return this.options(['none','single','multiple'],this.config.selection);}get discountsEnabled(){return this.config.discounts.enabled;}get discounts(){return this.config.columns.filter(c=>c.source!=='calculated').map(c=>({...c,typeOptions:this.options(['none','amount','percent'],c.discount)}));}
 get rules(){return this.config.rules.map(r=>({...r,compare:r.kind==='compare',isFormula:r.kind==='formula',formulaText:r.formulaText??formatTableFormula(r.formulaAst,this.config.columns),triggerOptions:[{value:'error',label:'True → show error',selected:r.formulaTrigger!=='valid'},{value:'valid',label:'False → show error',selected:r.formulaTrigger==='valid'}],tokens:this.config.columns.map(c=>({id:c.id,label:c.label})),kindOptions:this.options(['formula','compare','discount','net'],r.kind),leftOptions:this.refs(r.left),operatorOptions:this.options(['lte','lt','gte','gt','eq'],r.operator),rightKinds:this.options(['column','field','constant'],r.rightKind),isColumn:r.rightKind==='column',isField:r.rightKind==='field',isConstant:r.rightKind==='constant',rightOptions:this.refs(r.right),fieldOptions:this.options(this.allPaths,r.right),effects:this.options(['block','warn'],r.effect)}));}
 get totalsEnabled(){return this.config.totals.enabled;}get totalScopes(){return this.options(['all','selected'],this.config.totals.scope);}get aggregateOptions(){return this.options(['none','sum','average','min','max','count'],this.current?.aggregate||'none');}
 get dirtyText(){return this.dirty?'Draft changes · Apply to update canvas':'Saved configuration / default preview';}
 mark(){this.config=JSON.parse(JSON.stringify(this.config));this.dirty=true;this.error='';}
 tabChange(event){this.active=event.currentTarget.dataset.tab;}select(event){this.selected=event.currentTarget.dataset.id;if(!this.isDesign)this.active='Cell';}
 add(){const id='col'+Date.now().toString(36)+Math.random().toString(36).slice(2,5),c=newColumn(id);c.label='Column '+(this.config.columns.length+1);c.path=this.allPaths[0]||'';const refs=this.config.columns;c.left=refs[0]?.id||'';c.right=refs[1]?.id||refs[0]?.id||'';this.config.columns.push(c);this.selected=id;this.active='Cell';this.mark();}
 remove(){const id=this.selected;if(this.config.columns.some(c=>c.source==='calculated'&&((['add','subtract','multiply','divide'].includes(c.calculation)&&(c.left===id||c.right===id))||(c.calculation==='formula'&&(formulaReferences(c.formulaAst).includes(id)||this.draftReferences(c).includes(id)))))||this.config.rules.some(r=>Object.values(r.messageRefs||{}).includes(id)||(r.message||'').includes('{['+this.current.label+']}')||(r.kind==='compare'&&(r.left===id||(r.rightKind==='column'&&r.right===id)))||(r.kind==='formula'&&(formulaReferences(r.formulaAst).includes(id)||this.draftReferences(r).includes(id))))||(this.config.discounts.enabled&&[this.config.discounts.quantity,this.config.discounts.price].includes(id))){this.error='Remove references in calculations / rules before deleting this column.';return;}this.config.columns=this.config.columns.filter(c=>c.id!==id);this.selected=this.config.columns[0]?.id||'';this.mark();}
 move(event){const i=this.config.columns.findIndex(c=>c.id===this.selected),j=i+Number(event.currentTarget.dataset.direction);if(j>=0&&j<this.config.columns.length)[this.config.columns[i],this.config.columns[j]]=[this.config.columns[j],this.config.columns[i]];this.mark();}
 change(event){const {scope,key,id}=event.target.dataset;let value=event.target.type==='checkbox'?event.target.checked:event.target.type==='number'?(event.target.value===''?'':Number(event.target.value)):event.target.value;const target=scope==='design'?this.config:scope==='totals'?this.config.totals:scope==='discounts'?this.config.discounts:scope==='discountColumn'?this.config.columns.find(c=>c.id===id):scope==='rule'?this.config.rules.find(r=>r.id===id):this.current;target[key]=value;if(key==='inputType')target.defaultValue=value==='checkbox'?false:'';if(scope!=='rule'&&key==='source'&&value==='calculated'){target.calculation='formula';target.formulaText='0';}if(scope==='rule'&&key==='kind'&&value==='formula'&&!target.formulaAst)target.formulaText='FALSE';if(scope==='rule'&&key==='rightKind')target.right=value==='constant'?0:value==='field'?this.allPaths[0]||'':this.config.columns[0]?.id||'';this.mark();}
 draftReferences(target){try{return target.formulaText!==undefined?formulaReferences(parseTableFormula(target.formulaText,this.config.columns)):[];}catch(e){return [];}}
 addFormula(){this.add();this.current.source='calculated';this.current.calculation='formula';this.current.formulaText='0';this.mark();}
 insertToken(event){const {id,rule}=event.currentTarget.dataset;const col=this.config.columns.find(c=>c.id===id);const control=rule?[...this.template.querySelectorAll('textarea[data-scope="rule"]')].find(el=>el.dataset.id===rule):this.template.querySelector('textarea[data-key="formulaText"]');if(!control)return;const token='['+col.label+']';control.setRangeText(token,control.selectionStart,control.selectionEnd,'end');const target=rule?this.config.rules.find(r=>r.id===rule):this.current;target.formulaText=control.value;this.mark();control.focus();}
 addRule(){this.config.rules.push({id:'rule'+Date.now().toString(36)+Math.random().toString(36).slice(2,5),enabled:true,kind:'formula',formulaTrigger:'error',formulaText:'FALSE',left:this.config.columns.find(c=>c.source==='input')?.id||this.config.columns[0]?.id||'',operator:'lte',rightKind:'field',right:this.allPaths.find(p=>/stock/i.test(p))||this.allPaths[0]||'',effect:'block',message:'Row validation failed.'});this.mark();}
 removeRule(event){this.config.rules=this.config.rules.filter(r=>r.id!==event.currentTarget.dataset.id);this.mark();}
 addTotals(){for(const calculation of ['gross','discountAmount','discountPercent','net']){if(!this.config.columns.some(c=>c.source==='calculated'&&c.calculation===calculation))this.config.columns.push({...newColumn('total'+calculation),label:({gross:'Gross amount',discountAmount:'Total discount ₹',discountPercent:'Effective discount %',net:'Net amount'})[calculation],source:'calculated',calculation,group:'Calculated',align:'right'});}for(const kind of ['discount','net'])if(!this.config.rules.some(r=>r.kind===kind))this.config.rules.push({id:'limit'+kind,enabled:true,kind,effect:'block',message:kind==='discount'?'Effective discount {value}% exceeds 100%.':'Net amount {value} must be ≥ 0.'});this.mark();}
 apply(){try{validateTableConfig(this.config);this.dispatchEvent(new CustomEvent('propertychange',{detail:{key:'tableConfig',value:JSON.parse(JSON.stringify(this.config))}}));this.dirty=false;this.error='';}catch(e){this.error=e.message;}}
}
