import {validateTabConfig} from 'c/builderTabModel';
import {componentDefinition,defaultProperties,isSelectionType,palette,containers,canContain} from 'c/builderRegistry';
export function effectiveInputType(node){return node.type==='price'?'number':node.type==='search'?'search':node.props.inputType||'text';}
export function inputPattern(node){const p=node.props,type=effectiveInputType(node);if(p.textFormat==='custom')return p.pattern||'';if(type==='phone')return '[0-9]{10}';if(type==='tel')return '(?=.*[0-9])[+]?[0-9 ()-]+';return {letters:'[A-Za-z ]+',alphanumeric:'[A-Za-z0-9 ]+',digits:'[0-9]+'}[p.textFormat]||'';}
export function inputProperties(node){const type=effectiveInputType(node),boolean=['checkbox','toggle'].includes(type),numeric=type==='number',temporal=['date','datetime-local','time'].includes(type),strings=!boolean&&!numeric&&!temporal;
 const allowed={min:numeric||temporal,max:numeric||temporal,step:numeric,minLength:strings,maxLength:strings,textFormat:strings,pattern:strings&&node.props.textFormat==='custom',messageRequired:true,messageType:!boolean,messageMin:numeric||temporal,messageMax:numeric||temporal,messageStep:numeric,messageShort:strings,messageLong:strings,messagePattern:strings,toggleActive:type==='toggle',toggleInactive:type==='toggle',placeholder:!boolean};
 return (componentDefinition(node.type)?.properties||[]).filter(p=>allowed[p.key]!==false).map(p=>{if(p.key==='textFormat'&&['phone','tel','email','url'].includes(type))return {...p,values:['any','custom']};if(p.key==='value')return {...p,type:boolean?'checkbox':numeric?'number':type==='phone'?'tel':type,optional:true,min:undefined,max:undefined};if(['min','max'].includes(p.key))return {...p,type:numeric?'number':type,optional:true};return p;});
}
const present=v=>v!==undefined&&v!==null&&v!=='';
function temporalValue(type,value){const s=String(value);if(type==='time'){if(!/^\d{2}:\d{2}(?::\d{2}(?:\.\d+)?)?$/.test(s))return NaN;const parts=s.split(':').map(Number);return parts[0]<24&&parts[1]<60&&(parts[2]??0)<60?parts[0]*3600+parts[1]*60+(parts[2]||0):NaN;}if(type==='date'){if(!/^\d{4}-\d{2}-\d{2}$/.test(s))return NaN;const ms=Date.parse(s+'T00:00:00Z');return Number.isFinite(ms)&&new Date(ms).toISOString().slice(0,10)===s?ms:NaN;}return /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(?::\d{2}(?:\.\d+)?)?(?:Z|[+-]\d{2}:\d{2})?$/.test(s)&&Number.isFinite(temporalValue('date',s.slice(0,10)))?Date.parse(s):NaN;}
export function validateInputConfig(node){const p=node.props,type=effectiveInputType(node),numeric=type==='number',temporal=['date','datetime-local','time'].includes(type),strings=!numeric&&!temporal&&!['checkbox','toggle'].includes(type);
 if(numeric||temporal){for(const key of ['min','max'])if(present(p[key])&&!Number.isFinite(numeric?Number(p[key]):temporalValue(type,p[key])))throw Error('Invalid '+key+' for '+type);if(present(p.min)&&present(p.max)&&(numeric?Number(p.min)>Number(p.max):temporalValue(type,p.min)>temporalValue(type,p.max)))throw Error('Minimum must not exceed maximum');}
 if(numeric&&present(p.step)&&p.step!=='any'&&(!Number.isFinite(Number(p.step))||Number(p.step)<=0))throw Error('Step must be a positive number or any');
 if(strings){for(const key of ['minLength','maxLength'])if(present(p[key])&&(!Number.isInteger(Number(p[key]))||Number(p[key])<0))throw Error('Character limits must be non-negative whole numbers');if(present(p.minLength)&&present(p.maxLength)&&Number(p.minLength)>Number(p.maxLength))throw Error('Minimum characters must not exceed maximum characters');const pattern=inputPattern(node);if(pattern){try{new RegExp('^(?:'+pattern+')$','u');}catch(e){throw Error('Invalid regular expression');}}}
}
export function validateInputValue(node,value,checkRequired=true){const p=node.props,type=effectiveInputType(node);if(p.disabled||p.mode==='read')return '';const fail=(key,message)=>p[key]||message;
 if(['checkbox','toggle'].includes(type)){if(checkRequired&&p.required&&value!==true&&value!=='true')return fail('messageRequired','Select this option.');return [true,false,'true','false','',undefined,null].includes(value)?'':fail('messageType','Use true or false.');}
 if(!present(value))return checkRequired&&p.required?fail('messageRequired','Complete this field.'):'';
 const v=String(value);if(type==='number'){if(!/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?$/i.test(v)||!Number.isFinite(Number(v)))return fail('messageType','Enter a valid number.');const n=Number(v);if(present(p.min)&&n<Number(p.min))return fail('messageMin','Minimum value is '+p.min+'.');if(present(p.max)&&n>Number(p.max))return fail('messageMax','Maximum value is '+p.max+'.');const step=present(p.step)?p.step:1;if(step!=='any'){const diff=(n-(present(p.min)?Number(p.min):0))/Number(step);if(Math.abs(diff-Math.round(diff))>1e-7)return fail('messageStep','Use increments of '+step+'.');}return '';}
 if(['date','datetime-local','time'].includes(type)){const n=temporalValue(type,v);if(!Number.isFinite(n))return fail('messageType','Enter a valid '+type+'.');if(present(p.min)&&n<temporalValue(type,p.min))return fail('messageMin','Minimum value is '+p.min+'.');if(present(p.max)&&n>temporalValue(type,p.max))return fail('messageMax','Maximum value is '+p.max+'.');return '';}
 if(type==='email'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v))return fail('messageType','Enter a valid email address.');if(type==='url'){try{const u=new URL(v);if(!['http:','https:'].includes(u.protocol))throw Error();}catch(e){return fail('messageType','Enter a valid http or https URL.');}}
 if(present(p.minLength)&&v.length<Number(p.minLength))return fail('messageShort','Enter at least '+p.minLength+' characters.');if(present(p.maxLength)&&v.length>Number(p.maxLength))return fail('messageLong','Enter no more than '+p.maxLength+' characters.');const pattern=inputPattern(node);if(pattern&&!new RegExp('^(?:'+pattern+')$','u').test(v))return fail('messagePattern',type==='phone'?'Enter a 10 digit phone number.':type==='tel'?'Enter a valid telephone number.':'Use the allowed text format.');return '';
}
export function selectedValues(value,multiple){if(value===null||value===undefined||value==='')return [];let list;if(Array.isArray(value))list=value;else if(multiple&&String(value).trim().startsWith('[')){list=JSON.parse(value);if(!Array.isArray(list))throw Error('Selected values must be an array');}else list=multiple?String(value).split(',').map(v=>v.trim()).filter(Boolean):[value];if(list.some(v=>!['string','number'].includes(typeof v)))throw Error('Selections must contain scalar IDs or values');const ids=[...new Set(list.map(String))];return multiple?ids:ids.slice(0,1);}
function selectionPath(record,path){return String(path||'').split('.').reduce((value,key)=>value?.[key],record);}
export function selectionOptions(node){if(node.type==='multiPicklist'){if(node.data.boundSample!==undefined){const values=node.data.boundSample;if(!Array.isArray(values)||values.length>1000)throw Error('Picklist data must be an array of up to 1000 options');const mapped=values.map(r=>typeof r==='string'?{value:r,label:r,detail:''}:{value:String(r?.value??''),label:r?.label,detail:''});if(mapped.some(r=>!r.value||typeof r.label!=='string'||!r.label)||new Set(mapped.map(r=>r.value)).size!==mapped.length)throw Error('Pack options require unique value and label fields');return mapped;}const rows=String(node.props.options||'').split('\n').map(s=>s.trim()).filter(Boolean).map(s=>{const split=s.indexOf('|');return {value:split<0?s:s.slice(0,split).trim(),label:split<0?s:s.slice(split+1).trim(),detail:''};});if(rows.some(r=>!r.value||!r.label)||new Set(rows.map(r=>r.value)).size!==rows.length)throw Error('Options need unique values and non-empty labels');return rows;}
 const p=node.props;const rows=node.data.boundSample!==undefined?node.data.boundSample:JSON.parse(p.sampleRecords??defaultProperties(node.type).sampleRecords??'[]');if(!Array.isArray(rows)||rows.length>1000)throw Error('Lookup data must be an array of up to 1000 records');const result=rows.map(row=>{const id=selectionPath(row,p.valueField||'Id'),label=selectionPath(row,p.labelField||'Name'),detail=selectionPath(row,p.detailField||'');if(!row||typeof row!=='object'||id===undefined||id===null||!['string','number'].includes(typeof id)||!String(id)||typeof label!=='string'||!label)throw Error('Each lookup record needs a scalar ID and display text');return {value:String(id),label,detail:detail==null?'':String(detail)};});if(new Set(result.map(r=>r.value)).size!==result.length)throw Error('Lookup record IDs must be unique');return result;
}
export function selectionError(node,values){const p=node.props;if(p.disabled||p.mode==='read')return '';const min=Math.max(p.required?1:0,Number(p.minSelections)||0),max=node.type==='lookup'?1:Number(p.maxSelections)||50;if(values.length<min)return p.messageRequired||'Select at least '+min+' item(s).';if(values.length>max)return p.messageLimit||'Select no more than '+max+' item(s).';return '';}
export function validateSelectionConfig(node){const p=node.props;selectionOptions(node);const values=selectedValues(p.value,node.type!=='lookup');if(node.type!=='lookup'&&(!Number.isInteger(Number(p.minSelections??0))||!Number.isInteger(Number(p.maxSelections??50))||Number(p.minSelections??0)<0||Number(p.maxSelections??50)<1||Number(p.minSelections??0)>Number(p.maxSelections??50)))throw Error('Invalid selection limits');if(values.length>(node.type==='lookup'?1:Number(p.maxSelections)||50))throw Error('Default selections exceed the selection limit');}
export function validateProject(p){if(!p||![1,2].includes(p.schemaVersion)||typeof p.name!=='string'||!Array.isArray(p.nodes))throw Error('Invalid project file');if(!['lightning__RecordPage','lightning__AppPage','lightning__HomePage','lightning__RecordAction'].includes(p.target))throw Error('Invalid target');if(p.schemaVersion===2&&(!p.state||typeof p.state!=='object'||Array.isArray(p.state)||!Array.isArray(p.events)||!Array.isArray(p.actions)))throw Error('Invalid behavior sections');const ids=new Set();let count=0;function visit(nodes,depth,parentType=null){if(depth>15)throw Error('Maximum nesting is 15');for(const n of nodes){if(++count>500)throw Error('Maximum 500 components');if(!n||typeof n.id!=='string'||ids.has(n.id)||!palette.some(x=>x.type===n.type)||typeof n.label!=='string'||!Array.isArray(n.children)||!n.props||!n.data||!Array.isArray(n.rules)||!Array.isArray(n.actions)||!Array.isArray(n.connections))throw Error('Invalid component definition');if(!parentType&&!canContain(null,n.type))throw Error('Component requires a matching parent');if(!containers.includes(n.type)&&n.children.length)throw Error('Leaf components cannot contain children');for(const child of n.children){if(!canContain(n.type,child.type)&&n.type!=='tabs')throw Error('Invalid component nesting');}if(['input','search','price'].includes(n.type))validateInputConfig(n);if(isSelectionType(n.type))validateSelectionConfig(n);if(n.type==='tabs')validateTabConfig(n);ids.add(n.id);visit(n.children,depth+1,n.type);}}visit(p.nodes,0);return p;}
export function ruleMatches(rule,state){const a=state[rule.field],b=rule.value;switch(rule.operator){case 'equals':return String(a)===String(b);case 'not equals':return String(a)!==String(b);case 'contains':return String(a??'').includes(String(b));case 'blank':return a==null||a==='';case 'greater than':return Number(a)>Number(b);default:return false;}}
export function visible(node,state){const rules=node.rules.filter(r=>r.effect==='Visible');if(!rules.length)return true;return rules.reduce((result,r,i)=>i===0?ruleMatches(r,state):(r.join==='OR'?result||ruleMatches(r,state):result&&ruleMatches(r,state)),true);}
