import {assertType} from 'c/builderExpression';
import {createStateStore} from 'c/builderStateStore';
const values=['input','search','price','textarea','richText','combobox','radioGroup','checkboxGroup','dualListbox','inputField','outputField','helptext','badge','pill','lookup','multiLookup','multiPicklist'];
export const stateTypes=['Text','Number','Boolean','Date','List','Object'];
export const supportsValueBinding=node=>values.includes(node?.type);
export const selectionValue=node=>['lookup','multiLookup','multiPicklist'].includes(node?.type);
export function valueType(node){if(['multiLookup','multiPicklist'].includes(node.type))return 'List';const t=node.type==='price'?'number':node.type==='search'?'search':node.props.inputType;if(['checkbox','toggle'].includes(t))return 'Boolean';if(t==='number')return 'Number';if(t==='date')return 'Date';return 'Text';}
export const compatibleValueTypes=node=>['outputField','helptext','badge','pill'].includes(node.type)?['Text','Number','Boolean','Date']:[valueType(node)];
export function parseStateValue(value,type){let result=value;if(type==='Number'&&typeof value==='string'){if(!/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?$/i.test(value.trim())||!Number.isFinite(Number(value)))throw Error('Enter a valid Number');result=Number(value);}if(type==='Boolean'&&typeof value==='string'){if(!['true','false'].includes(value))throw Error('Choose True or False');result=value==='true';}if(['Object','List'].includes(type)&&typeof value==='string')result=JSON.parse(value);assertType(result,type);return result;}
export function stateDefinitions(state={}){const definitions=state.variables??[];if(!Array.isArray(definitions)||definitions.length>100)throw Error('State supports up to 100 variables');const keys=new Set();for(const d of definitions){if(!d||typeof d.key!=='string'||!/^[A-Za-z][A-Za-z0-9_]{0,63}$/.test(d.key)||['__proto__','prototype','constructor'].includes(d.key)||keys.has(d.key))throw Error('State variable keys must be safe and unique');if(!stateTypes.includes(d.type)||d.kind&&d.kind!=='variable')throw Error('Invalid state variable type or kind');assertType(d.defaultValue,d.type);keys.add(d.key);}return definitions;}
export function validateValueBindings(nodes,state={}){const specs=new Map(stateDefinitions(state).map(d=>[d.key,d]));const visit=n=>{const b=n.data.valueBinding;if(b){if(!supportsValueBinding(n)||!['state','pack'].includes(b.source))throw Error('Invalid value binding');if(b.source==='pack'){if(selectionValue(n))throw Error('Lookup Packs supply options; bind selected values to State');}else if(typeof b.key!=='string')throw Error('Invalid state binding key');if(b.source==='state'&&b.key){const d=specs.get(b.key);if(!d)throw Error('Bound state variable was removed: '+b.key);if(!compatibleValueTypes(n).includes(d.type))throw Error('Binding requires '+valueType(n)+' state: '+n.label);}}n.children.forEach(visit);};nodes.forEach(visit);return nodes;}
export function packValue(node,value){const types=compatibleValueTypes(node);if(types.length>1){if(value===null||value===undefined)return '';if(!types.some(t=>{try{assertType(value,t);return true;}catch{return false;}}))throw Error('Choose a scalar Data Pack field');return value;}const type=types[0];if(type==='Text'){if(value!==null&&typeof value==='object')throw Error('Choose a scalar Data Pack field');return String(value??'');}return parseStateValue(value,type);}
export function createBindingResolver(){let signature='',defs=[],sessions=new Map();
 function configure(state={}){const next=stateDefinitions(state),sig=JSON.stringify(next);if(sig===signature)return;defs=JSON.parse(sig);signature=sig;sessions=new Map();}
 function session(scope){if(!sessions.has(scope))sessions.set(scope,createStateStore(defs));return sessions.get(scope);}
 function resolve(nodes,scope){const result=JSON.parse(JSON.stringify(nodes));const visit=n=>{const b=n.data.valueBinding;if(b?.source==='pack'){try{if(n.data.boundError)throw Error(n.data.boundError);if(!n.data.packBinding?.packId)throw Error('Choose a Data Pack');if(n.data.boundSample===undefined)throw Error('Choose a published Pack field');n.props.value=packValue(n,n.data.boundSample);}catch(e){n.data.boundError=e.message;}}if(b?.source==='state'){try{if(!b.key)throw Error('Choose a State variable');const store=session(scope);if(!store.has(b.key))throw Error('Missing State variable: '+b.key);if(!compatibleValueTypes(n).includes(store.type(b.key)))throw Error('Binding requires '+valueType(n));n.props.value=store.read(b.key);}catch(e){n.data.boundError=e.message;}}n.children.forEach(visit);};result.forEach(visit);return result;}
 function write(node,value,scope){const b=node.data.valueBinding;if(b?.source!=='state')return null;if(node.props.disabled||node.props.mode==='read')throw Error('Component is read-only');const store=session(scope);if(store.type(b.key)!==valueType(node))throw Error('Binding requires '+valueType(node));if(node.type==='lookup'&&value===null)value='';return store.write(b.key,parseStateValue(value,store.type(b.key)),{origin:node.id});}
 function reset(scope){if(scope)sessions.delete(scope);else sessions.clear();}
 return {configure,resolve,write,reset,snapshot:scope=>session(scope).snapshot(),read:(key,scope)=>session(scope).read(key)};
}
