import {LightningElement,api} from 'lwc';
import {tableConfig,tableRows,evaluateTableRow,tableOutput,aggregateValues,resolveTableRowIds,buildTableEvent} from 'c/builderTableModel';
export default class BuilderTable extends LightningElement {
 page=1;sortColumn='';sortDirection='asc';sourceSignature='';_node;signature='';inputs={};selection=[];changedIds=[];rowIds=[];identityError='';temporaryIds=new Map();lastEvent=null;outputPacks={};detailRow=null;focusDetail=false;message='';@api preview=false;
 @api get node(){return this._node;}set node(n){const signature=JSON.stringify([n.id,n.props.tableConfig,n.data.packBinding]);const reset=signature!==this.signature;this._node=n;if(reset){this.signature=signature;this.page=1;this.sortColumn='';this.inputs={};this.selection=[];this.changedIds=[];this.temporaryIds=new Map();this.lastEvent=null;this.outputPacks={};this.detailRow=null;this.message='';}try{this.rowIds=resolveTableRowIds(tableRows(n),this.config.identity,this.temporaryIds);this.identityError='';this.page=Math.min(this.page,Math.max(1,Math.ceil(this.rowIds.length/(this.config.view.pageSize||this.rowIds.length||1))));const existing=new Set(this.rowIds);this.inputs=Object.fromEntries(Object.entries(this.inputs).filter(([id])=>existing.has(id)));this.selection=this.selection.filter(id=>existing.has(id));this.changedIds=this.changedIds.filter(id=>existing.has(id));}catch(e){this.rowIds=[];this.identityError=e.message;}}

 renderedCallback(){if(this.focusDetail){this.focusDetail=false;this.template.querySelector('[data-close-detail]')?.focus();}const signature=JSON.stringify([this.signature,this.node.data.boundSample,this.node.data.boundError]);if(signature!==this.sourceSignature){this.sourceSignature=signature;if(!this.sourceError)this.emit('sourcechange');}}
 get config(){return tableConfig(this.node);}get sourceError(){if(this.identityError)return this.identityError;try{tableRows(this.node);return '';}catch(e){return e.message;}}
 get source(){if(this.identityError)return [];try{return tableRows(this.node);}catch(e){return [];}}
 get columns(){return this.config.columns.filter(c=>c.visible).map(c=>({...c,style:`width:${c.width}px;min-width:${c.width}px;text-align:${c.align};`}));}
 get groups(){const groups=[];this.columns.forEach(c=>{const last=groups[groups.length-1];if(last&&last.label===c.group)last.span++;else groups.push({id:c.id,label:c.group||'Fields',span:1});});return groups;}
 get grouped(){return this.config.grouped;}get hasSelection(){return this.config.selection!=='none';}get selectType(){return this.config.selection==='single'?'radio':'checkbox';}get selectName(){return 'table-'+this.node.id;}
 get tableClass(){const c=this.config;return `table ${c.density==='compact'?'compact':''} ${c.striped?'striped':''} ${c.grid?'grid':''}`;}
 get evaluated(){const c=this.config;return this.source.map((row,i)=>{const rowId=this.rowIds[i],inputs=Object.prototype.hasOwnProperty.call(this.inputs,rowId)?this.inputs[rowId]:{};return {row,index:i,rowId,inputs,result:evaluateTableRow(row,inputs,c)};});}
 get rows(){let evaluated=this.evaluated;if(this.sortColumn){evaluated=[...evaluated].sort((a,b)=>{const x=a.result.values[this.sortColumn],y=b.result.values[this.sortColumn];const n=typeof x==='number'&&typeof y==='number'?x-y:String(x??'').localeCompare(String(y??''));return (this.sortDirection==='desc'?-n:n)||a.index-b.index;});}if(this.config.view.pageSize)evaluated=evaluated.slice((this.page-1)*this.config.view.pageSize,this.page*this.config.view.pageSize);return evaluated.map(({row,index,rowId,result})=>({key:rowId,errorKey:'error-'+rowId,index,rowId,selected:this.selection.includes(rowId),cls:result.issues.length?'invalid':'',error:result.issues.map(i=>(i.effect==='warn'?'Warning: ':'')+i.message).join(' · '),hasError:!!result.issues.length,cells:this.columns.map(c=>({id:c.id,value:result.values[c.id]??'',checked:result.values[c.id]===true,isInput:c.source==='input'&&!c.readonly,isCheckbox:c.source==='input'&&!c.readonly&&c.inputType==='checkbox',isTextInput:c.source==='input'&&!c.readonly&&c.inputType!=='checkbox',type:c.inputType,required:c.required,min:c.min!==''?c.min:undefined,max:c.max!==''?c.max:undefined,step:'any',style:c.style,label:c.label+' row '+(index+1),invalid:result.issues.some(i=>i.column===c.id),display:typeof result.values[c.id]==='number'?Number(result.values[c.id].toFixed(2)).toLocaleString('en-IN'):String(result.values[c.id]??'—')}))}));}
 get totalsEnabled(){return !!this.config.totals?.enabled;}get totalScopeLabel(){return this.config.totals?.scope==='selected'?'Selected rows':'All rows';}get totalCells(){const rows=this.evaluated.filter(r=>this.config.totals?.scope!=='selected'||this.selection.includes(r.rowId));return this.columns.map(c=>{let display='';try{if(c.aggregate&&c.aggregate!=='none'){const n=aggregateValues(rows.map(r=>r.result.values[c.id]),c.aggregate);display=n===null?'—':n.toLocaleString('en-IN',{maximumFractionDigits:2});}}catch(e){display='Invalid value';}return {id:c.id,display,style:c.style};});}
 get colspan(){return this.columns.length+(this.hasSelection?1:0)+(this.hasRowActions?1:0);}get noRows(){return !this.source.length;}get blocked(){return !!this.sourceError||this.evaluated.some(r=>!r.result.valid);}get summary(){return `${this.source.length} rows · ${this.selection.length} selected · ${this.evaluated.filter(r=>r.result.issues.length).length} rows with issues`;}
 selectColumn(event){event.stopPropagation();if(!this.preview)this.dispatchEvent(new CustomEvent('tablecolumnselect',{detail:{nodeId:this.node.id,columnId:event.currentTarget.dataset.id},bubbles:true,composed:true}));}
 get sortable(){return this.config.view.sortable;}get sortOptions(){return this.columns.map(c=>({...c,selected:c.id===this.sortColumn}));}get descending(){return this.sortDirection==='desc';}get pagination(){return this.config.view.pageSize>0;}get pageCount(){return Math.max(1,Math.ceil(this.source.length/(this.config.view.pageSize||this.source.length||1)));}get pageLabel(){return 'Page '+this.page+' of '+this.pageCount;}get firstPage(){return this.page<=1;}get lastPage(){return this.page>=this.pageCount;}sortChange(event){this.sortColumn=event.target.value;this.page=1;}sortReverse(){this.sortDirection=this.sortDirection==='asc'?'desc':'asc';}pageMove(event){this.page=Math.min(this.pageCount,Math.max(1,this.page+Number(event.currentTarget.dataset.direction)));}
 closeDetail(event){event?.stopPropagation();this.detailRow=null;this.template.querySelector('[data-rowid]')?.focus();}detailKey(event){if(event.key==='Escape')this.closeDetail(event);if(event.key==='Tab'){event.preventDefault();this.template.querySelector('[data-close-detail]')?.focus();}}stopDetail(event){event.stopPropagation();}
 get hasRowActions(){return this.config.eventActions.some(a=>a.enabled&&a.event==='rowaction');}get eventJson(){return this.lastEvent?JSON.stringify(this.lastEvent,null,2):'No row activity yet';}get hasDetail(){return !!this.detailRow;}get detailJson(){return JSON.stringify(this.detailRow,null,2);}
 edit(event){if(this.sourceError)return;const {rowid,id}=event.target.dataset,c=this.config.columns.find(c=>c.id===id),previous=this.evaluated.find(r=>r.rowId===rowid)?.result.values[id];const value=c.inputType==='checkbox'?event.target.checked:event.target.value;this.inputs={...this.inputs,[rowid]:{...(Object.prototype.hasOwnProperty.call(this.inputs,rowid)?this.inputs[rowid]:{}),[c.key]:value}};this.changedIds=[...new Set([...this.changedIds,rowid])];this.message='Unsaved sample changes';this.emit('cellchange',{rowId:rowid,changedField:c.key,previousValue:previous,value});}
 select(event){if(this.sourceError)return;const rowId=event.target.dataset.rowid;this.selection=this.config.selection==='single'?[rowId]:event.target.checked?[...new Set([...this.selection,rowId])]:this.selection.filter(x=>x!==rowId);this.emit('rowselection',{rowId});}
 rowAction(event){event.stopPropagation();this.emit('rowaction',{rowId:event.currentTarget.dataset.rowid});}
 emit(type,context={}){if(this.sourceError)return;const detail=buildTableEvent(this.config,this.evaluated,this.selection,this.changedIds,type,context,this.outputPacks);this.outputPacks=detail.outputPacks;this.lastEvent=detail;const opened=detail.actionResults.find(a=>a.action==='openRow'&&!a.error);if(opened){this.detailRow={rowId:opened.rowId,data:opened.row};this.focusDetail=true;}this.dispatchEvent(new CustomEvent('tablechange',{detail,bubbles:false}));}
 save(){if(this.blocked)return;this.emit('save');this.message=this.lastEvent?.valid?'Sample rows saved in Preview only · no Salesforce write':'Output / action failed; inspect row activity.';}
}
